//
//  Waves01.swift
//  TowerDefense9
//
//  Created by Stephen Tim on 2025/3/17.
//

let waves01 = Waves(
    waves: [
        Wave(MonsterCode: [
            MonsterCode(type: .spider, level: 1),
            MonsterCode(type: .spider, level: 1),
            MonsterCode(type: .spider, level: 1),
            MonsterCode(type: .spider, level: 1),
            MonsterCode(type: .spider, level: 2)]), // 1
        Wave(MonsterCode: [
            MonsterCode(type: .snail, level: 1),
            MonsterCode(type: .snail, level: 1),
            MonsterCode(type: .snail, level: 1),
            MonsterCode(type: .snail, level: 1),
            MonsterCode(type: .snail, level: 2)]),
        Wave(MonsterCode: [
            MonsterCode(type: .snail, level: 1),
            MonsterCode(type: .snail, level: 1),
            MonsterCode(type: .spider, level: 1),
            MonsterCode(type: .snail, level: 1),
            MonsterCode(type: .snail, level: 1),
            MonsterCode(type: .spider, level: 1),
            MonsterCode(type: .snail, level: 1),
            MonsterCode(type: .snail, level: 1),
            MonsterCode(type: .spider, level: 1),
            MonsterCode(type: .spider, level: 2)]),
        Wave(MonsterCode: [
            MonsterCode(type: .snail, level: 1),
            MonsterCode(type: .spider, level: 1),
            MonsterCode(type: .spider, level: 1),
            MonsterCode(type: .snail, level: 1),
            MonsterCode(type: .spider, level: 1),
            MonsterCode(type: .spider, level: 1),
            MonsterCode(type: .snail, level: 1),
            MonsterCode(type: .spider, level: 1),
            MonsterCode(type: .spider, level: 1),
            MonsterCode(type: .snail, level: 2)]),
        Wave(MonsterCode: [
            MonsterCode(type: .spider, level: 1),
            MonsterCode(type: .snail, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .spider, level: 1),
            MonsterCode(type: .snail, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .spider, level: 1),
            MonsterCode(type: .snail, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .crab, level: 2)]), // 5
        Wave(MonsterCode: [
            MonsterCode(type: .spider, level: 1),
            MonsterCode(type: .snail, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .alien, level: 1),
            MonsterCode(type: .spider, level: 1),
            MonsterCode(type: .snail, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .alien, level: 1),
            MonsterCode(type: .alien, level: 1),
            MonsterCode(type: .crab, level: 2)]),
        Wave(MonsterCode: [
            MonsterCode(type: .spider, level: 1),
            MonsterCode(type: .snail, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .alien, level: 1),
            MonsterCode(type: .ghost, level: 1),
            MonsterCode(type: .spider, level: 1),
            MonsterCode(type: .snail, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .alien, level: 1),
            MonsterCode(type: .ghost, level: 2)]),
        Wave(MonsterCode: [
            MonsterCode(type: .spider, level: 1),
            MonsterCode(type: .snail, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .alien, level: 1),
            MonsterCode(type: .ghost, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .crab, level: 2)]),
        Wave(MonsterCode: [
            MonsterCode(type: .spider, level: 1),
            MonsterCode(type: .snail, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .alien, level: 1),
            MonsterCode(type: .ghost, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .spider, level: 2)]),
        Wave(MonsterCode: [
            MonsterCode(type: .spider, level: 1),
            MonsterCode(type: .snail, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .alien, level: 1),
            MonsterCode(type: .ghost, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .snail, level: 2)]), // 10
        Wave(MonsterCode: [
            MonsterCode(type: .spider, level: 1),
            MonsterCode(type: .snail, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .alien, level: 1),
            MonsterCode(type: .ghost, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .crab, level: 2)]),
        Wave(MonsterCode: [
            MonsterCode(type: .spider, level: 1),
            MonsterCode(type: .snail, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .alien, level: 1),
            MonsterCode(type: .ghost, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .alien, level: 2)]),
        Wave(MonsterCode: [
            MonsterCode(type: .spider, level: 1),
            MonsterCode(type: .snail, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .alien, level: 1),
            MonsterCode(type: .ghost, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .ghost, level: 2)]),
        Wave(MonsterCode: [
            MonsterCode(type: .spider, level: 1),
            MonsterCode(type: .snail, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .alien, level: 1),
            MonsterCode(type: .ghost, level: 1),
            MonsterCode(type: .pumpkin, level: 1),
            MonsterCode(type: .pumpkin, level: 1),
            MonsterCode(type: .pumpkin, level: 1),
            MonsterCode(type: .pumpkin, level: 1),
            MonsterCode(type: .pumpkin, level: 2)]),
        Wave(MonsterCode: [
            MonsterCode(type: .pumpkin, level: 1),
            MonsterCode(type: .pumpkin, level: 1),
            MonsterCode(type: .spider, level: 1),
            MonsterCode(type: .alien, level: 1),
            MonsterCode(type: .ghost, level: 1),
            MonsterCode(type: .pumpkin, level: 1),
            MonsterCode(type: .pumpkin, level: 1),
            MonsterCode(type: .spider, level: 1),
            MonsterCode(type: .spider, level: 1),
            MonsterCode(type: .pumpkin, level: 3)]), // 15
        Wave(MonsterCode: [
            MonsterCode(type: .spider, level: 2),
            MonsterCode(type: .snail, level: 2),
            MonsterCode(type: .crab, level: 2),
            MonsterCode(type: .alien, level: 2),
            MonsterCode(type: .ghost, level: 2),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .dung, level: 3)]),
        Wave(MonsterCode: [
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .spider, level: 2),
            MonsterCode(type: .spider, level: 2),
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .spider, level: 2),
            MonsterCode(type: .spider, level: 2),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .dung, level: 3)]),
        Wave(MonsterCode: [
            MonsterCode(type: .crab, level: 2),
            MonsterCode(type: .crab, level: 2),
            MonsterCode(type: .crab, level: 2),
            MonsterCode(type: .crab, level: 2),
            MonsterCode(type: .crab, level: 2),
            MonsterCode(type: .crab, level: 2),
            MonsterCode(type: .crab, level: 2),
            MonsterCode(type: .crab, level: 2),
            MonsterCode(type: .crab, level: 2),
            MonsterCode(type: .crab, level: 3)]),
        Wave(MonsterCode: [
            MonsterCode(type: .alien, level: 2),
            MonsterCode(type: .alien, level: 2),
            MonsterCode(type: .alien, level: 2),
            MonsterCode(type: .alien, level: 2),
            MonsterCode(type: .alien, level: 2),
            MonsterCode(type: .alien, level: 2),
            MonsterCode(type: .alien, level: 2),
            MonsterCode(type: .alien, level: 2),
            MonsterCode(type: .alien, level: 2),
            MonsterCode(type: .alien, level: 3)]),
        Wave(MonsterCode: [
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .ghost, level: 2),
            MonsterCode(type: .ghost, level: 2),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .ghost, level: 2),
            MonsterCode(type: .ghost, level: 2),
            MonsterCode(type: .ghost, level: 2),
            MonsterCode(type: .pumpkin, level: 3)]), //20
        Wave(MonsterCode: [
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .pumpkin, level: 3)]),
        Wave(MonsterCode: [
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .dung, level: 3)]),
        Wave(MonsterCode: [
            MonsterCode(type: .eyes, level: 2),
            MonsterCode(type: .eyes, level: 2),
            MonsterCode(type: .spider, level: 2),
            MonsterCode(type: .snail, level: 2),
            MonsterCode(type: .eyes, level: 2),
            MonsterCode(type: .eyes, level: 2),
            MonsterCode(type: .eyes, level: 2),
            MonsterCode(type: .eyes, level: 2),
            MonsterCode(type: .eyes, level: 2),
            MonsterCode(type: .eyes, level: 3)]),
        Wave(MonsterCode: [
            MonsterCode(type: .pig, level: 2),
            MonsterCode(type: .pig, level: 2),
            MonsterCode(type: .spider, level: 2),
            MonsterCode(type: .spider, level: 2),
            MonsterCode(type: .pig, level: 2),
            MonsterCode(type: .pig, level: 2),
            MonsterCode(type: .spider, level: 2),
            MonsterCode(type: .pig, level: 2),
            MonsterCode(type: .pig, level: 2),
            MonsterCode(type: .pig, level: 3)]),
        Wave(MonsterCode: [
            MonsterCode(type: .elephant, level: 2),
            MonsterCode(type: .elephant, level: 2),
            MonsterCode(type: .spider, level: 2),
            MonsterCode(type: .spider, level: 2),
            MonsterCode(type: .elephant, level: 2),
            MonsterCode(type: .elephant, level: 2),
            MonsterCode(type: .elephant, level: 2),
            MonsterCode(type: .spider, level: 2),
            MonsterCode(type: .elephant, level: 2),
            MonsterCode(type: .elephant, level: 3)]), // 25
        Wave(MonsterCode: [
            MonsterCode(type: .crab, level: 2),
            MonsterCode(type: .crab, level: 3),
            MonsterCode(type: .crab, level: 2),
            MonsterCode(type: .crab, level: 2),
            MonsterCode(type: .crab, level: 3),
            MonsterCode(type: .crab, level: 2),
            MonsterCode(type: .crab, level: 2),
            MonsterCode(type: .crab, level: 3),
            MonsterCode(type: .crab, level: 2),
            MonsterCode(type: .crab, level: 4)]),
        Wave(MonsterCode: [
            MonsterCode(type: .alien, level: 2),
            MonsterCode(type: .alien, level: 3),
            MonsterCode(type: .alien, level: 2),
            MonsterCode(type: .alien, level: 2),
            MonsterCode(type: .alien, level: 3),
            MonsterCode(type: .alien, level: 2),
            MonsterCode(type: .alien, level: 2),
            MonsterCode(type: .alien, level: 3),
            MonsterCode(type: .alien, level: 2),
            MonsterCode(type: .alien, level: 4)]),
        Wave(MonsterCode: [
            MonsterCode(type: .ghost, level: 2),
            MonsterCode(type: .ghost, level: 3),
            MonsterCode(type: .ghost, level: 2),
            MonsterCode(type: .ghost, level: 2),
            MonsterCode(type: .ghost, level: 3),
            MonsterCode(type: .ghost, level: 2),
            MonsterCode(type: .ghost, level: 2),
            MonsterCode(type: .ghost, level: 3),
            MonsterCode(type: .ghost, level: 2),
            MonsterCode(type: .ghost, level: 4)]),
        Wave(MonsterCode: [
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .pumpkin, level: 3),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .pumpkin, level: 3),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .pumpkin, level: 3),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .pumpkin, level: 4)]),
        Wave(MonsterCode: [
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .dung, level: 3),
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .dung, level: 3),
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .dung, level: 3),
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .dung, level: 4)]), // 30
        Wave(MonsterCode: [
            MonsterCode(type: .eyes, level: 2),
            MonsterCode(type: .eyes, level: 3),
            MonsterCode(type: .eyes, level: 2),
            MonsterCode(type: .eyes, level: 2),
            MonsterCode(type: .eyes, level: 3),
            MonsterCode(type: .eyes, level: 2),
            MonsterCode(type: .eyes, level: 2),
            MonsterCode(type: .eyes, level: 3),
            MonsterCode(type: .eyes, level: 2),
            MonsterCode(type: .eyes, level: 4)]),
        Wave(MonsterCode: [
            MonsterCode(type: .pig, level: 2),
            MonsterCode(type: .pig, level: 3),
            MonsterCode(type: .pig, level: 2),
            MonsterCode(type: .pig, level: 2),
            MonsterCode(type: .pig, level: 3),
            MonsterCode(type: .pig, level: 2),
            MonsterCode(type: .pig, level: 2),
            MonsterCode(type: .pig, level: 3),
            MonsterCode(type: .pig, level: 2),
            MonsterCode(type: .pig, level: 4)]),
        Wave(MonsterCode: [
            MonsterCode(type: .elephant, level: 2),
            MonsterCode(type: .elephant, level: 3),
            MonsterCode(type: .elephant, level: 2),
            MonsterCode(type: .elephant, level: 2),
            MonsterCode(type: .elephant, level: 3),
            MonsterCode(type: .elephant, level: 2),
            MonsterCode(type: .elephant, level: 2),
            MonsterCode(type: .elephant, level: 3),
            MonsterCode(type: .elephant, level: 2),
            MonsterCode(type: .elephant, level: 4)]),
        Wave(MonsterCode: [
            MonsterCode(type: .devil, level: 2),
            MonsterCode(type: .devil, level: 3),
            MonsterCode(type: .spider, level: 2),
            MonsterCode(type: .spider, level: 2),
            MonsterCode(type: .crab, level: 3),
            MonsterCode(type: .devil, level: 2),
            MonsterCode(type: .spider, level: 2),
            MonsterCode(type: .crab, level: 3),
            MonsterCode(type: .devil, level: 2),
            MonsterCode(type: .devil, level: 4)]),
        Wave(MonsterCode: [
            MonsterCode(type: .devil, level: 2),
            MonsterCode(type: .devil, level: 3),
            MonsterCode(type: .devil, level: 2),
            MonsterCode(type: .devil, level: 2),
            MonsterCode(type: .devil, level: 3),
            MonsterCode(type: .devil, level: 2),
            MonsterCode(type: .devil, level: 2),
            MonsterCode(type: .devil, level: 3),
            MonsterCode(type: .devil, level: 2),
            MonsterCode(type: .devil, level: 4)]), // 35
        Wave(MonsterCode: [
            MonsterCode(type: .crab, level: 3),
            MonsterCode(type: .crab, level: 3),
            MonsterCode(type: .crab, level: 3),
            MonsterCode(type: .crab, level: 3),
            MonsterCode(type: .crab, level: 3),
            MonsterCode(type: .crab, level: 3),
            MonsterCode(type: .crab, level: 3),
            MonsterCode(type: .crab, level: 3),
            MonsterCode(type: .crab, level: 3),
            MonsterCode(type: .crab, level: 5)]),
        Wave(MonsterCode: [
            MonsterCode(type: .alien, level: 3),
            MonsterCode(type: .alien, level: 3),
            MonsterCode(type: .alien, level: 3),
            MonsterCode(type: .alien, level: 3),
            MonsterCode(type: .alien, level: 3),
            MonsterCode(type: .alien, level: 3),
            MonsterCode(type: .alien, level: 3),
            MonsterCode(type: .alien, level: 3),
            MonsterCode(type: .alien, level: 3),
            MonsterCode(type: .alien, level: 5)]),
        Wave(MonsterCode: [
            MonsterCode(type: .ghost, level: 3),
            MonsterCode(type: .ghost, level: 3),
            MonsterCode(type: .ghost, level: 3),
            MonsterCode(type: .ghost, level: 3),
            MonsterCode(type: .ghost, level: 3),
            MonsterCode(type: .ghost, level: 3),
            MonsterCode(type: .ghost, level: 3),
            MonsterCode(type: .ghost, level: 3),
            MonsterCode(type: .ghost, level: 3),
            MonsterCode(type: .ghost, level: 5)]),
        Wave(MonsterCode: [
            MonsterCode(type: .pumpkin, level: 3),
            MonsterCode(type: .pumpkin, level: 3),
            MonsterCode(type: .pumpkin, level: 3),
            MonsterCode(type: .pumpkin, level: 3),
            MonsterCode(type: .pumpkin, level: 3),
            MonsterCode(type: .pumpkin, level: 3),
            MonsterCode(type: .pumpkin, level: 3),
            MonsterCode(type: .pumpkin, level: 3),
            MonsterCode(type: .pumpkin, level: 3),
            MonsterCode(type: .pumpkin, level: 5)]),
        Wave(MonsterCode: [
            MonsterCode(type: .dung, level: 3),
            MonsterCode(type: .dung, level: 3),
            MonsterCode(type: .dung, level: 3),
            MonsterCode(type: .dung, level: 3),
            MonsterCode(type: .dung, level: 3),
            MonsterCode(type: .dung, level: 3),
            MonsterCode(type: .dung, level: 3),
            MonsterCode(type: .dung, level: 3),
            MonsterCode(type: .dung, level: 3),
            MonsterCode(type: .dung, level: 5)]), // 40
        Wave(MonsterCode: [
            MonsterCode(type: .eyes, level: 3),
            MonsterCode(type: .eyes, level: 3),
            MonsterCode(type: .eyes, level: 3),
            MonsterCode(type: .eyes, level: 3),
            MonsterCode(type: .eyes, level: 3),
            MonsterCode(type: .eyes, level: 3),
            MonsterCode(type: .eyes, level: 3),
            MonsterCode(type: .eyes, level: 3),
            MonsterCode(type: .eyes, level: 3),
            MonsterCode(type: .eyes, level: 5)]),
        Wave(MonsterCode: [
            MonsterCode(type: .pig, level: 3),
            MonsterCode(type: .pig, level: 3),
            MonsterCode(type: .pig, level: 3),
            MonsterCode(type: .pig, level: 3),
            MonsterCode(type: .pig, level: 3),
            MonsterCode(type: .pig, level: 3),
            MonsterCode(type: .pig, level: 3),
            MonsterCode(type: .pig, level: 3),
            MonsterCode(type: .pig, level: 3),
            MonsterCode(type: .pig, level: 5)]),
        Wave(MonsterCode: [
            MonsterCode(type: .elephant, level: 3),
            MonsterCode(type: .elephant, level: 3),
            MonsterCode(type: .elephant, level: 3),
            MonsterCode(type: .elephant, level: 3),
            MonsterCode(type: .elephant, level: 3),
            MonsterCode(type: .elephant, level: 3),
            MonsterCode(type: .elephant, level: 3),
            MonsterCode(type: .elephant, level: 3),
            MonsterCode(type: .elephant, level: 3),
            MonsterCode(type: .elephant, level: 5)]),
        Wave(MonsterCode: [
            MonsterCode(type: .devil, level: 3),
            MonsterCode(type: .devil, level: 3),
            MonsterCode(type: .spider, level: 3),
            MonsterCode(type: .spider, level: 3),
            MonsterCode(type: .crab, level: 3),
            MonsterCode(type: .devil, level: 3),
            MonsterCode(type: .spider, level: 3),
            MonsterCode(type: .crab, level: 3),
            MonsterCode(type: .devil, level: 3),
            MonsterCode(type: .devil, level: 5)]),
        Wave(MonsterCode: [
            MonsterCode(type: .devil, level: 3),
            MonsterCode(type: .devil, level: 3),
            MonsterCode(type: .devil, level: 3),
            MonsterCode(type: .devil, level: 3),
            MonsterCode(type: .devil, level: 3),
            MonsterCode(type: .devil, level: 3),
            MonsterCode(type: .devil, level: 3),
            MonsterCode(type: .devil, level: 3),
            MonsterCode(type: .devil, level: 3),
            MonsterCode(type: .devil, level: 5)]), // 45
        Wave(MonsterCode: [
            MonsterCode(type: .crab, level: 4),
            MonsterCode(type: .crab, level: 4),
            MonsterCode(type: .crab, level: 4),
            MonsterCode(type: .crab, level: 4),
            MonsterCode(type: .crab, level: 4),
            MonsterCode(type: .crab, level: 4),
            MonsterCode(type: .crab, level: 4),
            MonsterCode(type: .crab, level: 4),
            MonsterCode(type: .crab, level: 4),
            MonsterCode(type: .crab, level: 6)]),
        Wave(MonsterCode: [
            MonsterCode(type: .alien, level: 4),
            MonsterCode(type: .alien, level: 4),
            MonsterCode(type: .alien, level: 4),
            MonsterCode(type: .alien, level: 4),
            MonsterCode(type: .alien, level: 4),
            MonsterCode(type: .alien, level: 4),
            MonsterCode(type: .alien, level: 4),
            MonsterCode(type: .alien, level: 4),
            MonsterCode(type: .alien, level: 4),
            MonsterCode(type: .alien, level: 6)]),
        Wave(MonsterCode: [
            MonsterCode(type: .ghost, level: 4),
            MonsterCode(type: .ghost, level: 4),
            MonsterCode(type: .ghost, level: 4),
            MonsterCode(type: .ghost, level: 4),
            MonsterCode(type: .ghost, level: 4),
            MonsterCode(type: .ghost, level: 4),
            MonsterCode(type: .ghost, level: 4),
            MonsterCode(type: .ghost, level: 4),
            MonsterCode(type: .ghost, level: 4),
            MonsterCode(type: .ghost, level: 6)]),
        Wave(MonsterCode: [
            MonsterCode(type: .pumpkin, level: 4),
            MonsterCode(type: .pumpkin, level: 4),
            MonsterCode(type: .pumpkin, level: 4),
            MonsterCode(type: .pumpkin, level: 4),
            MonsterCode(type: .pumpkin, level: 4),
            MonsterCode(type: .pumpkin, level: 4),
            MonsterCode(type: .pumpkin, level: 4),
            MonsterCode(type: .pumpkin, level: 4),
            MonsterCode(type: .pumpkin, level: 4),
            MonsterCode(type: .pumpkin, level: 6)]),
        Wave(MonsterCode: [
            MonsterCode(type: .dung, level: 4),
            MonsterCode(type: .dung, level: 4),
            MonsterCode(type: .dung, level: 4),
            MonsterCode(type: .dung, level: 4),
            MonsterCode(type: .dung, level: 4),
            MonsterCode(type: .dung, level: 4),
            MonsterCode(type: .dung, level: 4),
            MonsterCode(type: .dung, level: 4),
            MonsterCode(type: .dung, level: 4),
            MonsterCode(type: .dung, level: 6)]), // 50
        Wave(MonsterCode: [
            MonsterCode(type: .eyes, level: 4),
            MonsterCode(type: .eyes, level: 4),
            MonsterCode(type: .eyes, level: 4),
            MonsterCode(type: .eyes, level: 4),
            MonsterCode(type: .eyes, level: 4),
            MonsterCode(type: .eyes, level: 4),
            MonsterCode(type: .eyes, level: 4),
            MonsterCode(type: .eyes, level: 4),
            MonsterCode(type: .eyes, level: 4),
            MonsterCode(type: .eyes, level: 6)]),
        Wave(MonsterCode: [
            MonsterCode(type: .pig, level: 4),
            MonsterCode(type: .pig, level: 4),
            MonsterCode(type: .pig, level: 4),
            MonsterCode(type: .pig, level: 4),
            MonsterCode(type: .pig, level: 4),
            MonsterCode(type: .pig, level: 4),
            MonsterCode(type: .pig, level: 4),
            MonsterCode(type: .pig, level: 4),
            MonsterCode(type: .pig, level: 4),
            MonsterCode(type: .pig, level: 6)]),
        Wave(MonsterCode: [
            MonsterCode(type: .elephant, level: 4),
            MonsterCode(type: .elephant, level: 4),
            MonsterCode(type: .elephant, level: 4),
            MonsterCode(type: .elephant, level: 4),
            MonsterCode(type: .elephant, level: 4),
            MonsterCode(type: .elephant, level: 4),
            MonsterCode(type: .elephant, level: 4),
            MonsterCode(type: .elephant, level: 4),
            MonsterCode(type: .elephant, level: 4),
            MonsterCode(type: .elephant, level: 6)]),
        Wave(MonsterCode: [
            MonsterCode(type: .devil, level: 4),
            MonsterCode(type: .devil, level: 4),
            MonsterCode(type: .spider, level: 4),
            MonsterCode(type: .spider, level: 4),
            MonsterCode(type: .crab, level: 4),
            MonsterCode(type: .devil, level: 4),
            MonsterCode(type: .spider, level: 4),
            MonsterCode(type: .crab, level: 4),
            MonsterCode(type: .devil, level: 4),
            MonsterCode(type: .devil, level: 6)]),
        Wave(MonsterCode: [
            MonsterCode(type: .devil, level: 4),
            MonsterCode(type: .devil, level: 4),
            MonsterCode(type: .devil, level: 4),
            MonsterCode(type: .devil, level: 4),
            MonsterCode(type: .devil, level: 4),
            MonsterCode(type: .devil, level: 4),
            MonsterCode(type: .devil, level: 4),
            MonsterCode(type: .devil, level: 4),
            MonsterCode(type: .devil, level: 4),
            MonsterCode(type: .devil, level: 6)]), // 55
        Wave(MonsterCode: [
            MonsterCode(type: .eyes, level: 5),
            MonsterCode(type: .eyes, level: 5),
            MonsterCode(type: .eyes, level: 5),
            MonsterCode(type: .eyes, level: 5),
            MonsterCode(type: .eyes, level: 5),
            MonsterCode(type: .eyes, level: 5),
            MonsterCode(type: .eyes, level: 5),
            MonsterCode(type: .eyes, level: 5),
            MonsterCode(type: .eyes, level: 5),
            MonsterCode(type: .eyes, level: 6)]),
        Wave(MonsterCode: [
            MonsterCode(type: .pig, level: 5),
            MonsterCode(type: .pig, level: 5),
            MonsterCode(type: .pig, level: 5),
            MonsterCode(type: .pig, level: 5),
            MonsterCode(type: .pig, level: 5),
            MonsterCode(type: .pig, level: 5),
            MonsterCode(type: .pig, level: 5),
            MonsterCode(type: .pig, level: 5),
            MonsterCode(type: .pig, level: 5),
            MonsterCode(type: .pig, level: 6)]),
        Wave(MonsterCode: [
            MonsterCode(type: .elephant, level: 5),
            MonsterCode(type: .elephant, level: 5),
            MonsterCode(type: .elephant, level: 5),
            MonsterCode(type: .elephant, level: 5),
            MonsterCode(type: .elephant, level: 5),
            MonsterCode(type: .elephant, level: 5),
            MonsterCode(type: .elephant, level: 5),
            MonsterCode(type: .elephant, level: 5),
            MonsterCode(type: .elephant, level: 5),
            MonsterCode(type: .elephant, level: 6)]),
        Wave(MonsterCode: [
            MonsterCode(type: .devil, level: 5),
            MonsterCode(type: .devil, level: 5),
            MonsterCode(type: .spider, level: 5),
            MonsterCode(type: .spider, level: 5),
            MonsterCode(type: .crab, level: 5),
            MonsterCode(type: .devil, level: 5),
            MonsterCode(type: .spider, level: 5),
            MonsterCode(type: .crab, level: 5),
            MonsterCode(type: .devil, level: 5),
            MonsterCode(type: .devil, level: 6)]),
        Wave(MonsterCode: [
            MonsterCode(type: .devil, level: 5),
            MonsterCode(type: .devil, level: 5),
            MonsterCode(type: .devil, level: 5),
            MonsterCode(type: .devil, level: 5),
            MonsterCode(type: .devil, level: 5),
            MonsterCode(type: .devil, level: 5),
            MonsterCode(type: .devil, level: 5),
            MonsterCode(type: .devil, level: 5),
            MonsterCode(type: .devil, level: 5),
            MonsterCode(type: .devil, level: 6)])] // 60
)
