//
//  Waves02.swift
//  TowerDefense9
//
//  Created by Stephen Tim on 2025/3/17.
//
//
//  Waves00.swift
//  TowerDefense9
//
//  Created by Stephen Tim on 2025/3/17.
//

let waves02 = Waves(
    waves: [
        Wave(MonsterCode: [
            MonsterCode(type: .snail, level: 1),
            MonsterCode(type: .snail, level: 1),
            MonsterCode(type: .snail, level: 1),
            MonsterCode(type: .snail, level: 1),
            MonsterCode(type: .snail, level: 1),
            MonsterCode(type: .snail, level: 1),
            MonsterCode(type: .snail, level: 1),
            MonsterCode(type: .snail, level: 1),
            MonsterCode(type: .snail, level: 1),
            MonsterCode(type: .snail, level: 1)]),  // 1
        Wave(MonsterCode: [
            MonsterCode(type: .spider, level: 1),
            MonsterCode(type: .spider, level: 1),
            MonsterCode(type: .spider, level: 1),
            MonsterCode(type: .spider, level: 1),
            MonsterCode(type: .spider, level: 1),
            MonsterCode(type: .spider, level: 1),
            MonsterCode(type: .spider, level: 1),
            MonsterCode(type: .spider, level: 1),
            MonsterCode(type: .spider, level: 1),
            MonsterCode(type: .spider, level: 1)]),  // 2
        Wave(MonsterCode: [
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .crab, level: 1),
            MonsterCode(type: .crab, level: 1)]),  // 3
        Wave(MonsterCode: [
            MonsterCode(type: .alien, level: 1),
            MonsterCode(type: .alien, level: 1),
            MonsterCode(type: .alien, level: 1),
            MonsterCode(type: .alien, level: 1),
            MonsterCode(type: .alien, level: 1),
            MonsterCode(type: .alien, level: 1),
            MonsterCode(type: .alien, level: 1),
            MonsterCode(type: .alien, level: 1),
            MonsterCode(type: .alien, level: 1),
            MonsterCode(type: .alien, level: 1)]),  // 4
        Wave(MonsterCode: [
            MonsterCode(type: .ghost, level: 1),
            MonsterCode(type: .ghost, level: 1),
            MonsterCode(type: .ghost, level: 1),
            MonsterCode(type: .ghost, level: 1),
            MonsterCode(type: .ghost, level: 1),
            MonsterCode(type: .ghost, level: 1),
            MonsterCode(type: .ghost, level: 1),
            MonsterCode(type: .ghost, level: 1),
            MonsterCode(type: .ghost, level: 1),
            MonsterCode(type: .ghost, level: 1)]), // 5
        Wave(MonsterCode: [
            MonsterCode(type: .pumpkin, level: 1),
            MonsterCode(type: .pumpkin, level: 1),
            MonsterCode(type: .pumpkin, level: 1),
            MonsterCode(type: .pumpkin, level: 1),
            MonsterCode(type: .pumpkin, level: 1),
            MonsterCode(type: .pumpkin, level: 1),
            MonsterCode(type: .pumpkin, level: 1),
            MonsterCode(type: .pumpkin, level: 1),
            MonsterCode(type: .pumpkin, level: 1),
            MonsterCode(type: .pumpkin, level: 1)]),  // 6
        Wave(MonsterCode: [
            MonsterCode(type: .dung, level: 1),
            MonsterCode(type: .dung, level: 1),
            MonsterCode(type: .dung, level: 1),
            MonsterCode(type: .dung, level: 1),
            MonsterCode(type: .dung, level: 1),
            MonsterCode(type: .dung, level: 1),
            MonsterCode(type: .dung, level: 1),
            MonsterCode(type: .dung, level: 1),
            MonsterCode(type: .dung, level: 1),
            MonsterCode(type: .dung, level: 1)]),  // 7
        Wave(MonsterCode: [
            MonsterCode(type: .eyes, level: 1),
            MonsterCode(type: .eyes, level: 1),
            MonsterCode(type: .eyes, level: 1),
            MonsterCode(type: .eyes, level: 1),
            MonsterCode(type: .eyes, level: 1),
            MonsterCode(type: .eyes, level: 1),
            MonsterCode(type: .eyes, level: 1),
            MonsterCode(type: .eyes, level: 1),
            MonsterCode(type: .eyes, level: 1),
            MonsterCode(type: .eyes, level: 1)]),  // 8
        Wave(MonsterCode: [
            MonsterCode(type: .pig, level: 1),
            MonsterCode(type: .pig, level: 1),
            MonsterCode(type: .pig, level: 1),
            MonsterCode(type: .pig, level: 1),
            MonsterCode(type: .pig, level: 1),
            MonsterCode(type: .pig, level: 1),
            MonsterCode(type: .pig, level: 1),
            MonsterCode(type: .pig, level: 1),
            MonsterCode(type: .pig, level: 1),
            MonsterCode(type: .pig, level: 1)]),  // 9
        Wave(MonsterCode: [
            MonsterCode(type: .elephant, level: 1),
            MonsterCode(type: .elephant, level: 1),
            MonsterCode(type: .elephant, level: 1),
            MonsterCode(type: .elephant, level: 1),
            MonsterCode(type: .elephant, level: 1),
            MonsterCode(type: .elephant, level: 1),
            MonsterCode(type: .elephant, level: 1),
            MonsterCode(type: .elephant, level: 1),
            MonsterCode(type: .elephant, level: 1),
            MonsterCode(type: .elephant, level: 1)]),  // 10
        Wave(MonsterCode: [
            MonsterCode(type: .snail, level: 2),
            MonsterCode(type: .snail, level: 2),
            MonsterCode(type: .snail, level: 2),
            MonsterCode(type: .spider, level: 2),
            MonsterCode(type: .spider, level: 2),
            MonsterCode(type: .spider, level: 2),
            MonsterCode(type: .crab, level: 2),
            MonsterCode(type: .crab, level: 2),
            MonsterCode(type: .crab, level: 2),
            MonsterCode(type: .snail, level: 2),
            MonsterCode(type: .snail, level: 2),
            MonsterCode(type: .snail, level: 2),
            MonsterCode(type: .spider, level: 2),
            MonsterCode(type: .spider, level: 2),
            MonsterCode(type: .spider, level: 2),
            MonsterCode(type: .crab, level: 2),
            MonsterCode(type: .crab, level: 2),
            MonsterCode(type: .crab, level: 2),
            MonsterCode(type: .snail, level: 3),
            MonsterCode(type: .spider, level: 3),
            MonsterCode(type: .crab, level: 3)]),  // 11
        Wave(MonsterCode: [
            MonsterCode(type: .spider, level: 2),
            MonsterCode(type: .spider, level: 2),
            MonsterCode(type: .spider, level: 2),
            MonsterCode(type: .crab, level: 2),
            MonsterCode(type: .crab, level: 2),
            MonsterCode(type: .crab, level: 2),
            MonsterCode(type: .alien, level: 2),
            MonsterCode(type: .alien, level: 2),
            MonsterCode(type: .alien, level: 2),
            MonsterCode(type: .spider, level: 2),
            MonsterCode(type: .spider, level: 2),
            MonsterCode(type: .spider, level: 2),
            MonsterCode(type: .crab, level: 2),
            MonsterCode(type: .crab, level: 2),
            MonsterCode(type: .crab, level: 2),
            MonsterCode(type: .alien, level: 2),
            MonsterCode(type: .alien, level: 2),
            MonsterCode(type: .alien, level: 2),
            MonsterCode(type: .spider, level: 3),
            MonsterCode(type: .crab, level: 3),
            MonsterCode(type: .alien, level: 3)]),  // 12
        Wave(MonsterCode: [
            MonsterCode(type: .crab, level: 2),
            MonsterCode(type: .crab, level: 2),
            MonsterCode(type: .crab, level: 2),
            MonsterCode(type: .alien, level: 2),
            MonsterCode(type: .alien, level: 2),
            MonsterCode(type: .alien, level: 2),
            MonsterCode(type: .ghost, level: 2),
            MonsterCode(type: .ghost, level: 2),
            MonsterCode(type: .ghost, level: 2),
            MonsterCode(type: .crab, level: 2),
            MonsterCode(type: .crab, level: 2),
            MonsterCode(type: .crab, level: 2),
            MonsterCode(type: .alien, level: 2),
            MonsterCode(type: .alien, level: 2),
            MonsterCode(type: .alien, level: 2),
            MonsterCode(type: .ghost, level: 2),
            MonsterCode(type: .ghost, level: 2),
            MonsterCode(type: .ghost, level: 2),
            MonsterCode(type: .crab, level: 3),
            MonsterCode(type: .alien, level: 3),
            MonsterCode(type: .ghost, level: 3)]),  // 13
        Wave(MonsterCode: [
            MonsterCode(type: .alien, level: 2),
            MonsterCode(type: .alien, level: 2),
            MonsterCode(type: .alien, level: 2),
            MonsterCode(type: .ghost, level: 2),
            MonsterCode(type: .ghost, level: 2),
            MonsterCode(type: .ghost, level: 2),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .alien, level: 2),
            MonsterCode(type: .alien, level: 2),
            MonsterCode(type: .alien, level: 2),
            MonsterCode(type: .ghost, level: 2),
            MonsterCode(type: .ghost, level: 2),
            MonsterCode(type: .ghost, level: 2),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .alien, level: 3),
            MonsterCode(type: .ghost, level: 3),
            MonsterCode(type: .pumpkin, level: 3)]),  // 14
        Wave(MonsterCode: [
            MonsterCode(type: .ghost, level: 2),
            MonsterCode(type: .ghost, level: 2),
            MonsterCode(type: .ghost, level: 2),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .ghost, level: 2),
            MonsterCode(type: .ghost, level: 2),
            MonsterCode(type: .ghost, level: 2),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .ghost, level: 3),
            MonsterCode(type: .pumpkin, level: 3),
            MonsterCode(type: .dung, level: 3)]),  // 15
        Wave(MonsterCode: [
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .eyes, level: 2),
            MonsterCode(type: .eyes, level: 2),
            MonsterCode(type: .eyes, level: 2),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .eyes, level: 2),
            MonsterCode(type: .eyes, level: 2),
            MonsterCode(type: .eyes, level: 2),
            MonsterCode(type: .pumpkin, level: 3),
            MonsterCode(type: .dung, level: 3),
            MonsterCode(type: .eyes, level: 3)]),  // 16
        Wave(MonsterCode: [
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .eyes, level: 2),
            MonsterCode(type: .eyes, level: 2),
            MonsterCode(type: .eyes, level: 2),
            MonsterCode(type: .pig, level: 2),
            MonsterCode(type: .pig, level: 2),
            MonsterCode(type: .pig, level: 2),
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .eyes, level: 2),
            MonsterCode(type: .eyes, level: 2),
            MonsterCode(type: .eyes, level: 2),
            MonsterCode(type: .pig, level: 2),
            MonsterCode(type: .pig, level: 2),
            MonsterCode(type: .pig, level: 2),
            MonsterCode(type: .dung, level: 3),
            MonsterCode(type: .eyes, level: 3),
            MonsterCode(type: .pig, level: 3)]),  // 17
        Wave(MonsterCode: [
            MonsterCode(type: .eyes, level: 2),
            MonsterCode(type: .eyes, level: 2),
            MonsterCode(type: .eyes, level: 2),
            MonsterCode(type: .pig, level: 2),
            MonsterCode(type: .pig, level: 2),
            MonsterCode(type: .pig, level: 2),
            MonsterCode(type: .elephant, level: 2),
            MonsterCode(type: .elephant, level: 2),
            MonsterCode(type: .elephant, level: 2),
            MonsterCode(type: .eyes, level: 2),
            MonsterCode(type: .eyes, level: 2),
            MonsterCode(type: .eyes, level: 2),
            MonsterCode(type: .pig, level: 2),
            MonsterCode(type: .pig, level: 2),
            MonsterCode(type: .pig, level: 2),
            MonsterCode(type: .elephant, level: 2),
            MonsterCode(type: .elephant, level: 2),
            MonsterCode(type: .elephant, level: 2),
            MonsterCode(type: .eyes, level: 3),
            MonsterCode(type: .pig, level: 3),
            MonsterCode(type: .elephant, level: 3)]),  // 18
        Wave(MonsterCode: [
            MonsterCode(type: .pig, level: 2),
            MonsterCode(type: .pig, level: 2),
            MonsterCode(type: .pig, level: 2),
            MonsterCode(type: .elephant, level: 2),
            MonsterCode(type: .elephant, level: 2),
            MonsterCode(type: .elephant, level: 2),
            MonsterCode(type: .devil, level: 2),
            MonsterCode(type: .devil, level: 2),
            MonsterCode(type: .devil, level: 2),
            MonsterCode(type: .pig, level: 2),
            MonsterCode(type: .pig, level: 2),
            MonsterCode(type: .pig, level: 2),
            MonsterCode(type: .elephant, level: 2),
            MonsterCode(type: .elephant, level: 2),
            MonsterCode(type: .elephant, level: 2),
            MonsterCode(type: .devil, level: 2),
            MonsterCode(type: .devil, level: 2),
            MonsterCode(type: .devil, level: 2),
            MonsterCode(type: .pig, level: 3),
            MonsterCode(type: .elephant, level: 3),
            MonsterCode(type: .devil, level: 3)]),  // 19
        Wave(MonsterCode: [
            MonsterCode(type: .snail, level: 2),
            MonsterCode(type: .spider, level: 2),
            MonsterCode(type: .crab, level: 2),
            MonsterCode(type: .alien, level: 2),
            MonsterCode(type: .ghost, level: 2),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .eyes, level: 2),
            MonsterCode(type: .pig, level: 2),
            MonsterCode(type: .elephant, level: 2),
            MonsterCode(type: .devil, level: 2),
            MonsterCode(type: .snail, level: 3),
            MonsterCode(type: .spider, level: 3),
            MonsterCode(type: .crab, level: 3),
            MonsterCode(type: .alien, level: 3),
            MonsterCode(type: .ghost, level: 3),
            MonsterCode(type: .pumpkin, level: 3),
            MonsterCode(type: .dung, level: 3),
            MonsterCode(type: .eyes, level: 3),
            MonsterCode(type: .pig, level: 3),
            MonsterCode(type: .elephant, level: 3),
            MonsterCode(type: .devil, level: 3)]),  // 20
        Wave(MonsterCode: [
            MonsterCode(type: .snail, level: 2),
            MonsterCode(type: .snail, level: 3),
            MonsterCode(type: .spider, level: 2),
            MonsterCode(type: .spider, level: 3),
            MonsterCode(type: .snail, level: 2),
            MonsterCode(type: .snail, level: 3),
            MonsterCode(type: .spider, level: 2),
            MonsterCode(type: .spider, level: 3),
            MonsterCode(type: .snail, level: 2),
            MonsterCode(type: .snail, level: 3),
            MonsterCode(type: .spider, level: 2),
            MonsterCode(type: .spider, level: 3),
            MonsterCode(type: .snail, level: 2),
            MonsterCode(type: .snail, level: 3),
            MonsterCode(type: .spider, level: 2),
            MonsterCode(type: .spider, level: 3),
            MonsterCode(type: .snail, level: 3),
            MonsterCode(type: .snail, level: 4),
            MonsterCode(type: .spider, level: 3),
            MonsterCode(type: .spider, level: 4)]),  // 21
        Wave(MonsterCode: [
            MonsterCode(type: .spider, level: 2),
            MonsterCode(type: .spider, level: 3),
            MonsterCode(type: .crab, level: 2),
            MonsterCode(type: .crab, level: 3),
            MonsterCode(type: .spider, level: 2),
            MonsterCode(type: .spider, level: 3),
            MonsterCode(type: .crab, level: 2),
            MonsterCode(type: .crab, level: 3),
            MonsterCode(type: .spider, level: 2),
            MonsterCode(type: .spider, level: 3),
            MonsterCode(type: .crab, level: 2),
            MonsterCode(type: .crab, level: 3),
            MonsterCode(type: .spider, level: 2),
            MonsterCode(type: .spider, level: 3),
            MonsterCode(type: .crab, level: 2),
            MonsterCode(type: .crab, level: 3),
            MonsterCode(type: .spider, level: 3),
            MonsterCode(type: .spider, level: 4),
            MonsterCode(type: .crab, level: 3),
            MonsterCode(type: .crab, level: 4)]),  // 22
        Wave(MonsterCode: [
            MonsterCode(type: .crab, level: 2),
            MonsterCode(type: .crab, level: 3),
            MonsterCode(type: .alien, level: 2),
            MonsterCode(type: .alien, level: 3),
            MonsterCode(type: .crab, level: 2),
            MonsterCode(type: .crab, level: 3),
            MonsterCode(type: .alien, level: 2),
            MonsterCode(type: .alien, level: 3),
            MonsterCode(type: .crab, level: 2),
            MonsterCode(type: .crab, level: 3),
            MonsterCode(type: .alien, level: 2),
            MonsterCode(type: .alien, level: 3),
            MonsterCode(type: .crab, level: 2),
            MonsterCode(type: .crab, level: 3),
            MonsterCode(type: .alien, level: 2),
            MonsterCode(type: .alien, level: 3),
            MonsterCode(type: .crab, level: 3),
            MonsterCode(type: .crab, level: 4),
            MonsterCode(type: .alien, level: 3),
            MonsterCode(type: .alien, level: 4)]),  // 23
        Wave(MonsterCode: [
            MonsterCode(type: .alien, level: 2),
            MonsterCode(type: .alien, level: 3),
            MonsterCode(type: .ghost, level: 2),
            MonsterCode(type: .ghost, level: 3),
            MonsterCode(type: .alien, level: 2),
            MonsterCode(type: .alien, level: 3),
            MonsterCode(type: .ghost, level: 2),
            MonsterCode(type: .ghost, level: 3),
            MonsterCode(type: .alien, level: 2),
            MonsterCode(type: .alien, level: 3),
            MonsterCode(type: .ghost, level: 2),
            MonsterCode(type: .ghost, level: 3),
            MonsterCode(type: .alien, level: 2),
            MonsterCode(type: .alien, level: 3),
            MonsterCode(type: .ghost, level: 2),
            MonsterCode(type: .ghost, level: 3),
            MonsterCode(type: .alien, level: 3),
            MonsterCode(type: .alien, level: 4),
            MonsterCode(type: .ghost, level: 3),
            MonsterCode(type: .ghost, level: 4)]),  // 24
        Wave(MonsterCode: [
            MonsterCode(type: .ghost, level: 2),
            MonsterCode(type: .ghost, level: 3),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .pumpkin, level: 3),
            MonsterCode(type: .ghost, level: 2),
            MonsterCode(type: .ghost, level: 3),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .pumpkin, level: 3),
            MonsterCode(type: .ghost, level: 2),
            MonsterCode(type: .ghost, level: 3),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .pumpkin, level: 3),
            MonsterCode(type: .ghost, level: 2),
            MonsterCode(type: .ghost, level: 3),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .pumpkin, level: 3),
            MonsterCode(type: .ghost, level: 3),
            MonsterCode(type: .ghost, level: 4),
            MonsterCode(type: .pumpkin, level: 3),
            MonsterCode(type: .pumpkin, level: 4)]), // 25
        Wave(MonsterCode: [
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .pumpkin, level: 3),
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .dung, level: 3),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .pumpkin, level: 3),
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .dung, level: 3),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .pumpkin, level: 3),
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .dung, level: 3),
            MonsterCode(type: .pumpkin, level: 2),
            MonsterCode(type: .pumpkin, level: 3),
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .dung, level: 3),
            MonsterCode(type: .pumpkin, level: 3),
            MonsterCode(type: .pumpkin, level: 4),
            MonsterCode(type: .dung, level: 3),
            MonsterCode(type: .dung, level: 4)]),  // 26
        Wave(MonsterCode: [
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .dung, level: 3),
            MonsterCode(type: .eyes, level: 2),
            MonsterCode(type: .eyes, level: 3),
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .dung, level: 3),
            MonsterCode(type: .eyes, level: 2),
            MonsterCode(type: .eyes, level: 3),
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .dung, level: 3),
            MonsterCode(type: .eyes, level: 2),
            MonsterCode(type: .eyes, level: 3),
            MonsterCode(type: .dung, level: 2),
            MonsterCode(type: .dung, level: 3),
            MonsterCode(type: .eyes, level: 2),
            MonsterCode(type: .eyes, level: 3),
            MonsterCode(type: .dung, level: 3),
            MonsterCode(type: .dung, level: 4),
            MonsterCode(type: .eyes, level: 3),
            MonsterCode(type: .eyes, level: 4)]),  // 27
        Wave(MonsterCode: [
            MonsterCode(type: .eyes, level: 2),
            MonsterCode(type: .eyes, level: 3),
            MonsterCode(type: .pig, level: 2),
            MonsterCode(type: .pig, level: 3),
            MonsterCode(type: .eyes, level: 2),
            MonsterCode(type: .eyes, level: 3),
            MonsterCode(type: .pig, level: 2),
            MonsterCode(type: .pig, level: 3),
            MonsterCode(type: .eyes, level: 2),
            MonsterCode(type: .eyes, level: 3),
            MonsterCode(type: .pig, level: 2),
            MonsterCode(type: .pig, level: 3),
            MonsterCode(type: .eyes, level: 2),
            MonsterCode(type: .eyes, level: 3),
            MonsterCode(type: .pig, level: 2),
            MonsterCode(type: .pig, level: 3),
            MonsterCode(type: .eyes, level: 3),
            MonsterCode(type: .eyes, level: 4),
            MonsterCode(type: .pig, level: 3),
            MonsterCode(type: .pig, level: 4)]),  // 28
        Wave(MonsterCode: [
            MonsterCode(type: .pig, level: 2),
            MonsterCode(type: .pig, level: 3),
            MonsterCode(type: .elephant, level: 2),
            MonsterCode(type: .elephant, level: 3),
            MonsterCode(type: .pig, level: 2),
            MonsterCode(type: .pig, level: 3),
            MonsterCode(type: .elephant, level: 2),
            MonsterCode(type: .elephant, level: 3),
            MonsterCode(type: .pig, level: 2),
            MonsterCode(type: .pig, level: 3),
            MonsterCode(type: .elephant, level: 2),
            MonsterCode(type: .elephant, level: 3),
            MonsterCode(type: .pig, level: 2),
            MonsterCode(type: .pig, level: 3),
            MonsterCode(type: .elephant, level: 2),
            MonsterCode(type: .elephant, level: 3),
            MonsterCode(type: .pig, level: 3),
            MonsterCode(type: .pig, level: 4),
            MonsterCode(type: .elephant, level: 3),
            MonsterCode(type: .elephant, level: 4)]),  // 29
        Wave(MonsterCode: [
            MonsterCode(type: .elephant, level: 2),
            MonsterCode(type: .elephant, level: 3),
            MonsterCode(type: .devil, level: 2),
            MonsterCode(type: .devil, level: 3),
            MonsterCode(type: .elephant, level: 2),
            MonsterCode(type: .elephant, level: 3),
            MonsterCode(type: .devil, level: 2),
            MonsterCode(type: .devil, level: 3),
            MonsterCode(type: .elephant, level: 2),
            MonsterCode(type: .elephant, level: 3),
            MonsterCode(type: .devil, level: 2),
            MonsterCode(type: .devil, level: 3),
            MonsterCode(type: .elephant, level: 2),
            MonsterCode(type: .elephant, level: 3),
            MonsterCode(type: .devil, level: 2),
            MonsterCode(type: .devil, level: 3),
            MonsterCode(type: .elephant, level: 3),
            MonsterCode(type: .elephant, level: 4),
            MonsterCode(type: .devil, level: 3),
            MonsterCode(type: .devil, level: 4)]), // 30
        Wave(MonsterCode: [
            MonsterCode(type: .snail, level: 4),
            MonsterCode(type: .snail, level: 4),
            MonsterCode(type: .snail, level: 4),
            MonsterCode(type: .snail, level: 4),
            MonsterCode(type: .snail, level: 4),
            MonsterCode(type: .snail, level: 4),
            MonsterCode(type: .snail, level: 4),
            MonsterCode(type: .snail, level: 4),
            MonsterCode(type: .snail, level: 4),
            MonsterCode(type: .snail, level: 4),
            MonsterCode(type: .snail, level: 4),
            MonsterCode(type: .snail, level: 4),
            MonsterCode(type: .snail, level: 4),
            MonsterCode(type: .snail, level: 4),
            MonsterCode(type: .snail, level: 4),
            MonsterCode(type: .snail, level: 4),
            MonsterCode(type: .snail, level: 4),
            MonsterCode(type: .snail, level: 4),
            MonsterCode(type: .snail, level: 4),
            MonsterCode(type: .devil, level: 5)]),  // 31
        Wave(MonsterCode: [
            MonsterCode(type: .spider, level: 4),
            MonsterCode(type: .spider, level: 4),
            MonsterCode(type: .spider, level: 4),
            MonsterCode(type: .spider, level: 4),
            MonsterCode(type: .spider, level: 4),
            MonsterCode(type: .spider, level: 4),
            MonsterCode(type: .spider, level: 4),
            MonsterCode(type: .spider, level: 4),
            MonsterCode(type: .spider, level: 4),
            MonsterCode(type: .spider, level: 4),
            MonsterCode(type: .spider, level: 4),
            MonsterCode(type: .spider, level: 4),
            MonsterCode(type: .spider, level: 4),
            MonsterCode(type: .spider, level: 4),
            MonsterCode(type: .spider, level: 4),
            MonsterCode(type: .spider, level: 4),
            MonsterCode(type: .spider, level: 4),
            MonsterCode(type: .spider, level: 4),
            MonsterCode(type: .spider, level: 4),
            MonsterCode(type: .devil, level: 5)]),  // 32
        Wave(MonsterCode: [
            MonsterCode(type: .crab, level: 4),
            MonsterCode(type: .crab, level: 4),
            MonsterCode(type: .crab, level: 4),
            MonsterCode(type: .crab, level: 4),
            MonsterCode(type: .crab, level: 4),
            MonsterCode(type: .crab, level: 4),
            MonsterCode(type: .crab, level: 4),
            MonsterCode(type: .crab, level: 4),
            MonsterCode(type: .crab, level: 4),
            MonsterCode(type: .crab, level: 4),
            MonsterCode(type: .crab, level: 4),
            MonsterCode(type: .crab, level: 4),
            MonsterCode(type: .crab, level: 4),
            MonsterCode(type: .crab, level: 4),
            MonsterCode(type: .crab, level: 4),
            MonsterCode(type: .crab, level: 4),
            MonsterCode(type: .crab, level: 4),
            MonsterCode(type: .crab, level: 4),
            MonsterCode(type: .crab, level: 4),
            MonsterCode(type: .devil, level: 5)]),  // 33
        Wave(MonsterCode: [
            MonsterCode(type: .alien, level: 4),
            MonsterCode(type: .alien, level: 4),
            MonsterCode(type: .alien, level: 4),
            MonsterCode(type: .alien, level: 4),
            MonsterCode(type: .alien, level: 4),
            MonsterCode(type: .alien, level: 4),
            MonsterCode(type: .alien, level: 4),
            MonsterCode(type: .alien, level: 4),
            MonsterCode(type: .alien, level: 4),
            MonsterCode(type: .alien, level: 4),
            MonsterCode(type: .alien, level: 4),
            MonsterCode(type: .alien, level: 4),
            MonsterCode(type: .alien, level: 4),
            MonsterCode(type: .alien, level: 4),
            MonsterCode(type: .alien, level: 4),
            MonsterCode(type: .alien, level: 4),
            MonsterCode(type: .alien, level: 4),
            MonsterCode(type: .alien, level: 4),
            MonsterCode(type: .alien, level: 4),
            MonsterCode(type: .devil, level: 5)]),  // 34
        Wave(MonsterCode: [
            MonsterCode(type: .ghost, level: 4),
            MonsterCode(type: .ghost, level: 4),
            MonsterCode(type: .ghost, level: 4),
            MonsterCode(type: .ghost, level: 4),
            MonsterCode(type: .ghost, level: 4),
            MonsterCode(type: .ghost, level: 4),
            MonsterCode(type: .ghost, level: 4),
            MonsterCode(type: .ghost, level: 4),
            MonsterCode(type: .ghost, level: 4),
            MonsterCode(type: .ghost, level: 4),
            MonsterCode(type: .ghost, level: 4),
            MonsterCode(type: .ghost, level: 4),
            MonsterCode(type: .ghost, level: 4),
            MonsterCode(type: .ghost, level: 4),
            MonsterCode(type: .ghost, level: 4),
            MonsterCode(type: .ghost, level: 4),
            MonsterCode(type: .ghost, level: 4),
            MonsterCode(type: .ghost, level: 4),
            MonsterCode(type: .ghost, level: 4),
            MonsterCode(type: .devil, level: 5)]), // 35
        Wave(MonsterCode: [
            MonsterCode(type: .pumpkin, level: 4),
            MonsterCode(type: .pumpkin, level: 4),
            MonsterCode(type: .pumpkin, level: 4),
            MonsterCode(type: .pumpkin, level: 4),
            MonsterCode(type: .pumpkin, level: 4),
            MonsterCode(type: .pumpkin, level: 4),
            MonsterCode(type: .pumpkin, level: 4),
            MonsterCode(type: .pumpkin, level: 4),
            MonsterCode(type: .pumpkin, level: 4),
            MonsterCode(type: .pumpkin, level: 4),
            MonsterCode(type: .pumpkin, level: 4),
            MonsterCode(type: .pumpkin, level: 4),
            MonsterCode(type: .pumpkin, level: 4),
            MonsterCode(type: .pumpkin, level: 4),
            MonsterCode(type: .pumpkin, level: 4),
            MonsterCode(type: .pumpkin, level: 4),
            MonsterCode(type: .pumpkin, level: 4),
            MonsterCode(type: .pumpkin, level: 4),
            MonsterCode(type: .pumpkin, level: 4),
            MonsterCode(type: .devil, level: 5)]),  // 36
        Wave(MonsterCode: [
            MonsterCode(type: .dung, level: 4),
            MonsterCode(type: .dung, level: 4),
            MonsterCode(type: .dung, level: 4),
            MonsterCode(type: .dung, level: 4),
            MonsterCode(type: .dung, level: 4),
            MonsterCode(type: .dung, level: 4),
            MonsterCode(type: .dung, level: 4),
            MonsterCode(type: .dung, level: 4),
            MonsterCode(type: .dung, level: 4),
            MonsterCode(type: .dung, level: 4),
            MonsterCode(type: .dung, level: 4),
            MonsterCode(type: .dung, level: 4),
            MonsterCode(type: .dung, level: 4),
            MonsterCode(type: .dung, level: 4),
            MonsterCode(type: .dung, level: 4),
            MonsterCode(type: .dung, level: 4),
            MonsterCode(type: .dung, level: 4),
            MonsterCode(type: .dung, level: 4),
            MonsterCode(type: .dung, level: 4),
            MonsterCode(type: .devil, level: 5)]),  // 37
        Wave(MonsterCode: [
            MonsterCode(type: .eyes, level: 4),
            MonsterCode(type: .eyes, level: 4),
            MonsterCode(type: .eyes, level: 4),
            MonsterCode(type: .eyes, level: 4),
            MonsterCode(type: .eyes, level: 4),
            MonsterCode(type: .eyes, level: 4),
            MonsterCode(type: .eyes, level: 4),
            MonsterCode(type: .eyes, level: 4),
            MonsterCode(type: .eyes, level: 4),
            MonsterCode(type: .eyes, level: 4),
            MonsterCode(type: .eyes, level: 4),
            MonsterCode(type: .eyes, level: 4),
            MonsterCode(type: .eyes, level: 4),
            MonsterCode(type: .eyes, level: 4),
            MonsterCode(type: .eyes, level: 4),
            MonsterCode(type: .eyes, level: 4),
            MonsterCode(type: .eyes, level: 4),
            MonsterCode(type: .eyes, level: 4),
            MonsterCode(type: .eyes, level: 4),
            MonsterCode(type: .devil, level: 5)]),  // 38
        Wave(MonsterCode: [
            MonsterCode(type: .pig, level: 4),
            MonsterCode(type: .pig, level: 4),
            MonsterCode(type: .pig, level: 4),
            MonsterCode(type: .pig, level: 4),
            MonsterCode(type: .pig, level: 4),
            MonsterCode(type: .pig, level: 4),
            MonsterCode(type: .pig, level: 4),
            MonsterCode(type: .pig, level: 4),
            MonsterCode(type: .pig, level: 4),
            MonsterCode(type: .pig, level: 4),
            MonsterCode(type: .pig, level: 4),
            MonsterCode(type: .pig, level: 4),
            MonsterCode(type: .pig, level: 4),
            MonsterCode(type: .pig, level: 4),
            MonsterCode(type: .pig, level: 4),
            MonsterCode(type: .pig, level: 4),
            MonsterCode(type: .pig, level: 4),
            MonsterCode(type: .pig, level: 4),
            MonsterCode(type: .pig, level: 4),
            MonsterCode(type: .devil, level: 5)]),  // 39
        Wave(MonsterCode: [
            MonsterCode(type: .elephant, level: 4),
            MonsterCode(type: .elephant, level: 4),
            MonsterCode(type: .elephant, level: 4),
            MonsterCode(type: .elephant, level: 4),
            MonsterCode(type: .elephant, level: 4),
            MonsterCode(type: .elephant, level: 4),
            MonsterCode(type: .elephant, level: 4),
            MonsterCode(type: .elephant, level: 4),
            MonsterCode(type: .elephant, level: 4),
            MonsterCode(type: .elephant, level: 4),
            MonsterCode(type: .elephant, level: 4),
            MonsterCode(type: .elephant, level: 4),
            MonsterCode(type: .elephant, level: 4),
            MonsterCode(type: .elephant, level: 4),
            MonsterCode(type: .elephant, level: 4),
            MonsterCode(type: .elephant, level: 4),
            MonsterCode(type: .elephant, level: 4),
            MonsterCode(type: .elephant, level: 4),
            MonsterCode(type: .elephant, level: 4),
            MonsterCode(type: .elephant, level: 5)]),  // 40
        Wave(MonsterCode: [
            MonsterCode(type: .snail, level: 5),
            MonsterCode(type: .snail, level: 5),
            MonsterCode(type: .spider, level: 5),
            MonsterCode(type: .spider, level: 5),
            MonsterCode(type: .snail, level: 5),
            MonsterCode(type: .snail, level: 5),
            MonsterCode(type: .spider, level: 5),
            MonsterCode(type: .spider, level: 5),
            MonsterCode(type: .snail, level: 5),
            MonsterCode(type: .snail, level: 5),
            MonsterCode(type: .spider, level: 5),
            MonsterCode(type: .spider, level: 5),
            MonsterCode(type: .snail, level: 5),
            MonsterCode(type: .snail, level: 5),
            MonsterCode(type: .spider, level: 5),
            MonsterCode(type: .spider, level: 5),
            MonsterCode(type: .devil, level: 5),
            MonsterCode(type: .devil, level: 5),
            MonsterCode(type: .devil, level: 6),
            MonsterCode(type: .devil, level: 6)]),  // 41
        Wave(MonsterCode: [
            MonsterCode(type: .spider, level: 5),
            MonsterCode(type: .spider, level: 5),
            MonsterCode(type: .crab, level: 5),
            MonsterCode(type: .crab, level: 5),
            MonsterCode(type: .spider, level: 5),
            MonsterCode(type: .spider, level: 5),
            MonsterCode(type: .crab, level: 5),
            MonsterCode(type: .crab, level: 5),
            MonsterCode(type: .spider, level: 5),
            MonsterCode(type: .spider, level: 5),
            MonsterCode(type: .crab, level: 5),
            MonsterCode(type: .crab, level: 5),
            MonsterCode(type: .spider, level: 5),
            MonsterCode(type: .spider, level: 5),
            MonsterCode(type: .crab, level: 5),
            MonsterCode(type: .crab, level: 5),
            MonsterCode(type: .devil, level: 5),
            MonsterCode(type: .devil, level: 5),
            MonsterCode(type: .devil, level: 6),
            MonsterCode(type: .devil, level: 6)]),  // 42
        Wave(MonsterCode: [
            MonsterCode(type: .crab, level: 5),
            MonsterCode(type: .crab, level: 5),
            MonsterCode(type: .alien, level: 5),
            MonsterCode(type: .alien, level: 5),
            MonsterCode(type: .crab, level: 5),
            MonsterCode(type: .crab, level: 5),
            MonsterCode(type: .alien, level: 5),
            MonsterCode(type: .alien, level: 5),
            MonsterCode(type: .crab, level: 5),
            MonsterCode(type: .crab, level: 5),
            MonsterCode(type: .alien, level: 5),
            MonsterCode(type: .alien, level: 5),
            MonsterCode(type: .crab, level: 5),
            MonsterCode(type: .crab, level: 5),
            MonsterCode(type: .alien, level: 5),
            MonsterCode(type: .alien, level: 5),
            MonsterCode(type: .devil, level: 5),
            MonsterCode(type: .devil, level: 5),
            MonsterCode(type: .devil, level: 6),
            MonsterCode(type: .devil, level: 6)]),  // 43
        Wave(MonsterCode: [
            MonsterCode(type: .alien, level: 5),
            MonsterCode(type: .alien, level: 5),
            MonsterCode(type: .ghost, level: 5),
            MonsterCode(type: .ghost, level: 5),
            MonsterCode(type: .alien, level: 5),
            MonsterCode(type: .alien, level: 5),
            MonsterCode(type: .ghost, level: 5),
            MonsterCode(type: .ghost, level: 5),
            MonsterCode(type: .alien, level: 5),
            MonsterCode(type: .alien, level: 5),
            MonsterCode(type: .ghost, level: 5),
            MonsterCode(type: .ghost, level: 5),
            MonsterCode(type: .alien, level: 5),
            MonsterCode(type: .alien, level: 5),
            MonsterCode(type: .ghost, level: 5),
            MonsterCode(type: .ghost, level: 5),
            MonsterCode(type: .devil, level: 5),
            MonsterCode(type: .devil, level: 5),
            MonsterCode(type: .devil, level: 6),
            MonsterCode(type: .devil, level: 6)]),  // 44
        Wave(MonsterCode: [
            MonsterCode(type: .ghost, level: 5),
            MonsterCode(type: .ghost, level: 5),
            MonsterCode(type: .pumpkin, level: 5),
            MonsterCode(type: .pumpkin, level: 5),
            MonsterCode(type: .ghost, level: 5),
            MonsterCode(type: .ghost, level: 5),
            MonsterCode(type: .pumpkin, level: 5),
            MonsterCode(type: .pumpkin, level: 5),
            MonsterCode(type: .ghost, level: 5),
            MonsterCode(type: .ghost, level: 5),
            MonsterCode(type: .pumpkin, level: 5),
            MonsterCode(type: .pumpkin, level: 5),
            MonsterCode(type: .ghost, level: 5),
            MonsterCode(type: .ghost, level: 5),
            MonsterCode(type: .pumpkin, level: 5),
            MonsterCode(type: .pumpkin, level: 5),
            MonsterCode(type: .devil, level: 5),
            MonsterCode(type: .devil, level: 5),
            MonsterCode(type: .devil, level: 6),
            MonsterCode(type: .devil, level: 6)]), // 45
        Wave(MonsterCode: [
            MonsterCode(type: .pumpkin, level: 5),
            MonsterCode(type: .pumpkin, level: 5),
            MonsterCode(type: .dung, level: 5),
            MonsterCode(type: .dung, level: 5),
            MonsterCode(type: .pumpkin, level: 5),
            MonsterCode(type: .pumpkin, level: 5),
            MonsterCode(type: .dung, level: 5),
            MonsterCode(type: .dung, level: 5),
            MonsterCode(type: .pumpkin, level: 5),
            MonsterCode(type: .pumpkin, level: 5),
            MonsterCode(type: .dung, level: 5),
            MonsterCode(type: .dung, level: 5),
            MonsterCode(type: .pumpkin, level: 5),
            MonsterCode(type: .pumpkin, level: 5),
            MonsterCode(type: .dung, level: 5),
            MonsterCode(type: .dung, level: 5),
            MonsterCode(type: .devil, level: 5),
            MonsterCode(type: .devil, level: 5),
            MonsterCode(type: .devil, level: 6),
            MonsterCode(type: .devil, level: 6)]),  // 46
        Wave(MonsterCode: [
            MonsterCode(type: .dung, level: 5),
            MonsterCode(type: .dung, level: 5),
            MonsterCode(type: .eyes, level: 5),
            MonsterCode(type: .eyes, level: 5),
            MonsterCode(type: .dung, level: 5),
            MonsterCode(type: .dung, level: 5),
            MonsterCode(type: .eyes, level: 5),
            MonsterCode(type: .eyes, level: 5),
            MonsterCode(type: .dung, level: 5),
            MonsterCode(type: .dung, level: 5),
            MonsterCode(type: .eyes, level: 5),
            MonsterCode(type: .eyes, level: 5),
            MonsterCode(type: .dung, level: 5),
            MonsterCode(type: .dung, level: 5),
            MonsterCode(type: .eyes, level: 5),
            MonsterCode(type: .eyes, level: 5),
            MonsterCode(type: .devil, level: 5),
            MonsterCode(type: .devil, level: 5),
            MonsterCode(type: .devil, level: 6),
            MonsterCode(type: .devil, level: 6)]),  // 47
        Wave(MonsterCode: [
            MonsterCode(type: .eyes, level: 5),
            MonsterCode(type: .eyes, level: 5),
            MonsterCode(type: .pig, level: 5),
            MonsterCode(type: .pig, level: 5),
            MonsterCode(type: .eyes, level: 5),
            MonsterCode(type: .eyes, level: 5),
            MonsterCode(type: .pig, level: 5),
            MonsterCode(type: .pig, level: 5),
            MonsterCode(type: .eyes, level: 5),
            MonsterCode(type: .eyes, level: 5),
            MonsterCode(type: .pig, level: 5),
            MonsterCode(type: .pig, level: 5),
            MonsterCode(type: .eyes, level: 5),
            MonsterCode(type: .eyes, level: 5),
            MonsterCode(type: .pig, level: 5),
            MonsterCode(type: .pig, level: 5),
            MonsterCode(type: .devil, level: 5),
            MonsterCode(type: .devil, level: 5),
            MonsterCode(type: .devil, level: 6),
            MonsterCode(type: .devil, level: 6)]),  // 48
        Wave(MonsterCode: [
            MonsterCode(type: .pig, level: 5),
            MonsterCode(type: .pig, level: 5),
            MonsterCode(type: .elephant, level: 5),
            MonsterCode(type: .elephant, level: 5),
            MonsterCode(type: .pig, level: 5),
            MonsterCode(type: .pig, level: 5),
            MonsterCode(type: .elephant, level: 5),
            MonsterCode(type: .elephant, level: 5),
            MonsterCode(type: .pig, level: 5),
            MonsterCode(type: .pig, level: 5),
            MonsterCode(type: .elephant, level: 5),
            MonsterCode(type: .elephant, level: 5),
            MonsterCode(type: .pig, level: 5),
            MonsterCode(type: .pig, level: 5),
            MonsterCode(type: .elephant, level: 5),
            MonsterCode(type: .elephant, level: 5),
            MonsterCode(type: .devil, level: 5),
            MonsterCode(type: .devil, level: 5),
            MonsterCode(type: .devil, level: 6),
            MonsterCode(type: .devil, level: 6)]),  // 49
        Wave(MonsterCode: [
            MonsterCode(type: .elephant, level: 5),
            MonsterCode(type: .elephant, level: 5),
            MonsterCode(type: .devil, level: 5),
            MonsterCode(type: .devil, level: 5),
            MonsterCode(type: .elephant, level: 5),
            MonsterCode(type: .elephant, level: 5),
            MonsterCode(type: .devil, level: 5),
            MonsterCode(type: .devil, level: 5),
            MonsterCode(type: .elephant, level: 5),
            MonsterCode(type: .elephant, level: 5),
            MonsterCode(type: .devil, level: 5),
            MonsterCode(type: .devil, level: 5),
            MonsterCode(type: .elephant, level: 5),
            MonsterCode(type: .elephant, level: 5),
            MonsterCode(type: .devil, level: 5),
            MonsterCode(type: .devil, level: 5),
            MonsterCode(type: .devil, level: 5),
            MonsterCode(type: .devil, level: 5),
            MonsterCode(type: .devil, level: 6),
            MonsterCode(type: .devil, level: 6)]), // 50
        Wave(MonsterCode: [
            MonsterCode(type: .snail, level: 6),
            MonsterCode(type: .snail, level: 6),
            MonsterCode(type: .snail, level: 6),
            MonsterCode(type: .snail, level: 6),
            MonsterCode(type: .snail, level: 6),
            MonsterCode(type: .snail, level: 6),
            MonsterCode(type: .snail, level: 6),
            MonsterCode(type: .snail, level: 6),
            MonsterCode(type: .snail, level: 6),
            MonsterCode(type: .snail, level: 6),
            MonsterCode(type: .snail, level: 6),
            MonsterCode(type: .snail, level: 6),
            MonsterCode(type: .snail, level: 6),
            MonsterCode(type: .snail, level: 6),
            MonsterCode(type: .snail, level: 6),
            MonsterCode(type: .snail, level: 6),
            MonsterCode(type: .snail, level: 6),
            MonsterCode(type: .snail, level: 6),
            MonsterCode(type: .snail, level: 6),
            MonsterCode(type: .devil, level: 7)]),  // 51
        Wave(MonsterCode: [
            MonsterCode(type: .spider, level: 6),
            MonsterCode(type: .spider, level: 6),
            MonsterCode(type: .spider, level: 6),
            MonsterCode(type: .spider, level: 6),
            MonsterCode(type: .spider, level: 6),
            MonsterCode(type: .spider, level: 6),
            MonsterCode(type: .spider, level: 6),
            MonsterCode(type: .spider, level: 6),
            MonsterCode(type: .spider, level: 6),
            MonsterCode(type: .spider, level: 6),
            MonsterCode(type: .spider, level: 6),
            MonsterCode(type: .spider, level: 6),
            MonsterCode(type: .spider, level: 6),
            MonsterCode(type: .spider, level: 6),
            MonsterCode(type: .spider, level: 6),
            MonsterCode(type: .spider, level: 6),
            MonsterCode(type: .spider, level: 6),
            MonsterCode(type: .spider, level: 6),
            MonsterCode(type: .spider, level: 6),
            MonsterCode(type: .devil, level: 7)]),  // 52
        Wave(MonsterCode: [
            MonsterCode(type: .crab, level: 6),
            MonsterCode(type: .crab, level: 6),
            MonsterCode(type: .crab, level: 6),
            MonsterCode(type: .crab, level: 6),
            MonsterCode(type: .crab, level: 6),
            MonsterCode(type: .crab, level: 6),
            MonsterCode(type: .crab, level: 6),
            MonsterCode(type: .crab, level: 6),
            MonsterCode(type: .crab, level: 6),
            MonsterCode(type: .crab, level: 6),
            MonsterCode(type: .crab, level: 6),
            MonsterCode(type: .crab, level: 6),
            MonsterCode(type: .crab, level: 6),
            MonsterCode(type: .crab, level: 6),
            MonsterCode(type: .crab, level: 6),
            MonsterCode(type: .crab, level: 6),
            MonsterCode(type: .crab, level: 6),
            MonsterCode(type: .crab, level: 6),
            MonsterCode(type: .crab, level: 6),
            MonsterCode(type: .devil, level: 7)]),  // 53
        Wave(MonsterCode: [
            MonsterCode(type: .alien, level: 6),
            MonsterCode(type: .alien, level: 6),
            MonsterCode(type: .alien, level: 6),
            MonsterCode(type: .alien, level: 6),
            MonsterCode(type: .alien, level: 6),
            MonsterCode(type: .alien, level: 6),
            MonsterCode(type: .alien, level: 6),
            MonsterCode(type: .alien, level: 6),
            MonsterCode(type: .alien, level: 6),
            MonsterCode(type: .alien, level: 6),
            MonsterCode(type: .alien, level: 6),
            MonsterCode(type: .alien, level: 6),
            MonsterCode(type: .alien, level: 6),
            MonsterCode(type: .alien, level: 6),
            MonsterCode(type: .alien, level: 6),
            MonsterCode(type: .alien, level: 6),
            MonsterCode(type: .alien, level: 6),
            MonsterCode(type: .alien, level: 6),
            MonsterCode(type: .alien, level: 6),
            MonsterCode(type: .devil, level: 7)]),  // 54
        Wave(MonsterCode: [
            MonsterCode(type: .ghost, level: 6),
            MonsterCode(type: .ghost, level: 6),
            MonsterCode(type: .ghost, level: 6),
            MonsterCode(type: .ghost, level: 6),
            MonsterCode(type: .ghost, level: 6),
            MonsterCode(type: .ghost, level: 6),
            MonsterCode(type: .ghost, level: 6),
            MonsterCode(type: .ghost, level: 6),
            MonsterCode(type: .ghost, level: 6),
            MonsterCode(type: .ghost, level: 6),
            MonsterCode(type: .ghost, level: 6),
            MonsterCode(type: .ghost, level: 6),
            MonsterCode(type: .ghost, level: 6),
            MonsterCode(type: .ghost, level: 6),
            MonsterCode(type: .ghost, level: 6),
            MonsterCode(type: .ghost, level: 6),
            MonsterCode(type: .ghost, level: 6),
            MonsterCode(type: .ghost, level: 6),
            MonsterCode(type: .ghost, level: 6),
            MonsterCode(type: .devil, level: 7)]), // 55
        Wave(MonsterCode: [
            MonsterCode(type: .pumpkin, level: 6),
            MonsterCode(type: .pumpkin, level: 6),
            MonsterCode(type: .pumpkin, level: 6),
            MonsterCode(type: .pumpkin, level: 6),
            MonsterCode(type: .pumpkin, level: 6),
            MonsterCode(type: .pumpkin, level: 6),
            MonsterCode(type: .pumpkin, level: 6),
            MonsterCode(type: .pumpkin, level: 6),
            MonsterCode(type: .pumpkin, level: 6),
            MonsterCode(type: .pumpkin, level: 6),
            MonsterCode(type: .pumpkin, level: 6),
            MonsterCode(type: .pumpkin, level: 6),
            MonsterCode(type: .pumpkin, level: 6),
            MonsterCode(type: .pumpkin, level: 6),
            MonsterCode(type: .pumpkin, level: 6),
            MonsterCode(type: .pumpkin, level: 6),
            MonsterCode(type: .pumpkin, level: 6),
            MonsterCode(type: .pumpkin, level: 6),
            MonsterCode(type: .pumpkin, level: 6),
            MonsterCode(type: .devil, level: 7)]),  // 56
        Wave(MonsterCode: [
            MonsterCode(type: .dung, level: 6),
            MonsterCode(type: .dung, level: 6),
            MonsterCode(type: .dung, level: 6),
            MonsterCode(type: .dung, level: 6),
            MonsterCode(type: .dung, level: 6),
            MonsterCode(type: .dung, level: 6),
            MonsterCode(type: .dung, level: 6),
            MonsterCode(type: .dung, level: 6),
            MonsterCode(type: .dung, level: 6),
            MonsterCode(type: .dung, level: 6),
            MonsterCode(type: .dung, level: 6),
            MonsterCode(type: .dung, level: 6),
            MonsterCode(type: .dung, level: 6),
            MonsterCode(type: .dung, level: 6),
            MonsterCode(type: .dung, level: 6),
            MonsterCode(type: .dung, level: 6),
            MonsterCode(type: .dung, level: 6),
            MonsterCode(type: .dung, level: 6),
            MonsterCode(type: .dung, level: 6),
            MonsterCode(type: .devil, level: 7)]),  // 57
        Wave(MonsterCode: [
            MonsterCode(type: .eyes, level: 6),
            MonsterCode(type: .eyes, level: 6),
            MonsterCode(type: .eyes, level: 6),
            MonsterCode(type: .eyes, level: 6),
            MonsterCode(type: .eyes, level: 6),
            MonsterCode(type: .eyes, level: 6),
            MonsterCode(type: .eyes, level: 6),
            MonsterCode(type: .eyes, level: 6),
            MonsterCode(type: .eyes, level: 6),
            MonsterCode(type: .eyes, level: 6),
            MonsterCode(type: .eyes, level: 6),
            MonsterCode(type: .eyes, level: 6),
            MonsterCode(type: .eyes, level: 6),
            MonsterCode(type: .eyes, level: 6),
            MonsterCode(type: .eyes, level: 6),
            MonsterCode(type: .eyes, level: 6),
            MonsterCode(type: .eyes, level: 6),
            MonsterCode(type: .eyes, level: 6),
            MonsterCode(type: .eyes, level: 6),
            MonsterCode(type: .devil, level: 7)]),  // 58
        Wave(MonsterCode: [
            MonsterCode(type: .pig, level: 6),
            MonsterCode(type: .pig, level: 6),
            MonsterCode(type: .pig, level: 6),
            MonsterCode(type: .pig, level: 6),
            MonsterCode(type: .pig, level: 6),
            MonsterCode(type: .pig, level: 6),
            MonsterCode(type: .pig, level: 6),
            MonsterCode(type: .pig, level: 6),
            MonsterCode(type: .pig, level: 6),
            MonsterCode(type: .pig, level: 6),
            MonsterCode(type: .pig, level: 6),
            MonsterCode(type: .pig, level: 6),
            MonsterCode(type: .pig, level: 6),
            MonsterCode(type: .pig, level: 6),
            MonsterCode(type: .pig, level: 6),
            MonsterCode(type: .pig, level: 6),
            MonsterCode(type: .pig, level: 6),
            MonsterCode(type: .pig, level: 6),
            MonsterCode(type: .pig, level: 6),
            MonsterCode(type: .devil, level: 7)]),  // 59
        Wave(MonsterCode: [
            MonsterCode(type: .elephant, level: 6),
            MonsterCode(type: .elephant, level: 6),
            MonsterCode(type: .elephant, level: 6),
            MonsterCode(type: .elephant, level: 6),
            MonsterCode(type: .elephant, level: 6),
            MonsterCode(type: .elephant, level: 6),
            MonsterCode(type: .elephant, level: 6),
            MonsterCode(type: .elephant, level: 6),
            MonsterCode(type: .elephant, level: 6),
            MonsterCode(type: .elephant, level: 6),
            MonsterCode(type: .elephant, level: 6),
            MonsterCode(type: .elephant, level: 6),
            MonsterCode(type: .elephant, level: 6),
            MonsterCode(type: .elephant, level: 6),
            MonsterCode(type: .elephant, level: 6),
            MonsterCode(type: .elephant, level: 6),
            MonsterCode(type: .elephant, level: 6),
            MonsterCode(type: .elephant, level: 6),
            MonsterCode(type: .elephant, level: 6),
            MonsterCode(type: .elephant, level: 7)]),  // 60
        Wave(MonsterCode: [
            MonsterCode(type: .snail, level: 7),
            MonsterCode(type: .snail, level: 7),
            MonsterCode(type: .spider, level: 7),
            MonsterCode(type: .spider, level: 7),
            MonsterCode(type: .snail, level: 7),
            MonsterCode(type: .snail, level: 7),
            MonsterCode(type: .spider, level: 7),
            MonsterCode(type: .spider, level: 7),
            MonsterCode(type: .snail, level: 7),
            MonsterCode(type: .snail, level: 7),
            MonsterCode(type: .spider, level: 7),
            MonsterCode(type: .spider, level: 7),
            MonsterCode(type: .snail, level: 7),
            MonsterCode(type: .snail, level: 7),
            MonsterCode(type: .spider, level: 7),
            MonsterCode(type: .spider, level: 7),
            MonsterCode(type: .devil, level: 7),
            MonsterCode(type: .devil, level: 7),
            MonsterCode(type: .devil, level: 8),
            MonsterCode(type: .devil, level: 8)]),  // 61
        Wave(MonsterCode: [
            MonsterCode(type: .spider, level: 7),
            MonsterCode(type: .spider, level: 7),
            MonsterCode(type: .crab, level: 7),
            MonsterCode(type: .crab, level: 7),
            MonsterCode(type: .spider, level: 7),
            MonsterCode(type: .spider, level: 7),
            MonsterCode(type: .crab, level: 7),
            MonsterCode(type: .crab, level: 7),
            MonsterCode(type: .spider, level: 7),
            MonsterCode(type: .spider, level: 7),
            MonsterCode(type: .crab, level: 7),
            MonsterCode(type: .crab, level: 7),
            MonsterCode(type: .spider, level: 7),
            MonsterCode(type: .spider, level: 7),
            MonsterCode(type: .crab, level: 7),
            MonsterCode(type: .crab, level: 7),
            MonsterCode(type: .devil, level: 7),
            MonsterCode(type: .devil, level: 7),
            MonsterCode(type: .devil, level: 8),
            MonsterCode(type: .devil, level: 8)]),  // 62
        Wave(MonsterCode: [
            MonsterCode(type: .crab, level: 7),
            MonsterCode(type: .crab, level: 7),
            MonsterCode(type: .alien, level: 7),
            MonsterCode(type: .alien, level: 7),
            MonsterCode(type: .crab, level: 7),
            MonsterCode(type: .crab, level: 7),
            MonsterCode(type: .alien, level: 7),
            MonsterCode(type: .alien, level: 7),
            MonsterCode(type: .crab, level: 7),
            MonsterCode(type: .crab, level: 7),
            MonsterCode(type: .alien, level: 7),
            MonsterCode(type: .alien, level: 7),
            MonsterCode(type: .crab, level: 7),
            MonsterCode(type: .crab, level: 7),
            MonsterCode(type: .alien, level: 7),
            MonsterCode(type: .alien, level: 7),
            MonsterCode(type: .devil, level: 7),
            MonsterCode(type: .devil, level: 7),
            MonsterCode(type: .devil, level: 8),
            MonsterCode(type: .devil, level: 8)]),  // 63
        Wave(MonsterCode: [
            MonsterCode(type: .alien, level: 7),
            MonsterCode(type: .alien, level: 7),
            MonsterCode(type: .ghost, level: 7),
            MonsterCode(type: .ghost, level: 7),
            MonsterCode(type: .alien, level: 7),
            MonsterCode(type: .alien, level: 7),
            MonsterCode(type: .ghost, level: 7),
            MonsterCode(type: .ghost, level: 7),
            MonsterCode(type: .alien, level: 7),
            MonsterCode(type: .alien, level: 7),
            MonsterCode(type: .ghost, level: 7),
            MonsterCode(type: .ghost, level: 7),
            MonsterCode(type: .alien, level: 7),
            MonsterCode(type: .alien, level: 7),
            MonsterCode(type: .ghost, level: 7),
            MonsterCode(type: .ghost, level: 7),
            MonsterCode(type: .devil, level: 7),
            MonsterCode(type: .devil, level: 7),
            MonsterCode(type: .devil, level: 8),
            MonsterCode(type: .devil, level: 8)]),  // 64
        Wave(MonsterCode: [
            MonsterCode(type: .ghost, level: 7),
            MonsterCode(type: .ghost, level: 7),
            MonsterCode(type: .pumpkin, level: 7),
            MonsterCode(type: .pumpkin, level: 7),
            MonsterCode(type: .ghost, level: 7),
            MonsterCode(type: .ghost, level: 7),
            MonsterCode(type: .pumpkin, level: 7),
            MonsterCode(type: .pumpkin, level: 7),
            MonsterCode(type: .ghost, level: 7),
            MonsterCode(type: .ghost, level: 7),
            MonsterCode(type: .pumpkin, level: 7),
            MonsterCode(type: .pumpkin, level: 7),
            MonsterCode(type: .ghost, level: 7),
            MonsterCode(type: .ghost, level: 7),
            MonsterCode(type: .pumpkin, level: 7),
            MonsterCode(type: .pumpkin, level: 7),
            MonsterCode(type: .devil, level: 7),
            MonsterCode(type: .devil, level: 7),
            MonsterCode(type: .devil, level: 8),
            MonsterCode(type: .devil, level: 8)]), // 65
        Wave(MonsterCode: [
            MonsterCode(type: .pumpkin, level: 7),
            MonsterCode(type: .pumpkin, level: 7),
            MonsterCode(type: .dung, level: 7),
            MonsterCode(type: .dung, level: 7),
            MonsterCode(type: .pumpkin, level: 7),
            MonsterCode(type: .pumpkin, level: 7),
            MonsterCode(type: .dung, level: 7),
            MonsterCode(type: .dung, level: 7),
            MonsterCode(type: .pumpkin, level: 7),
            MonsterCode(type: .pumpkin, level: 7),
            MonsterCode(type: .dung, level: 7),
            MonsterCode(type: .dung, level: 7),
            MonsterCode(type: .pumpkin, level: 7),
            MonsterCode(type: .pumpkin, level: 7),
            MonsterCode(type: .dung, level: 7),
            MonsterCode(type: .dung, level: 7),
            MonsterCode(type: .devil, level: 7),
            MonsterCode(type: .devil, level: 7),
            MonsterCode(type: .devil, level: 8),
            MonsterCode(type: .devil, level: 8)]),  // 66
        Wave(MonsterCode: [
            MonsterCode(type: .dung, level: 7),
            MonsterCode(type: .dung, level: 7),
            MonsterCode(type: .eyes, level: 7),
            MonsterCode(type: .eyes, level: 7),
            MonsterCode(type: .dung, level: 7),
            MonsterCode(type: .dung, level: 7),
            MonsterCode(type: .eyes, level: 7),
            MonsterCode(type: .eyes, level: 7),
            MonsterCode(type: .dung, level: 7),
            MonsterCode(type: .dung, level: 7),
            MonsterCode(type: .eyes, level: 7),
            MonsterCode(type: .eyes, level: 7),
            MonsterCode(type: .dung, level: 7),
            MonsterCode(type: .dung, level: 7),
            MonsterCode(type: .eyes, level: 7),
            MonsterCode(type: .eyes, level: 7),
            MonsterCode(type: .devil, level: 7),
            MonsterCode(type: .devil, level: 7),
            MonsterCode(type: .devil, level: 8),
            MonsterCode(type: .devil, level: 8)]),  // 67
        Wave(MonsterCode: [
            MonsterCode(type: .eyes, level: 7),
            MonsterCode(type: .eyes, level: 7),
            MonsterCode(type: .pig, level: 7),
            MonsterCode(type: .pig, level: 7),
            MonsterCode(type: .eyes, level: 7),
            MonsterCode(type: .eyes, level: 7),
            MonsterCode(type: .pig, level: 7),
            MonsterCode(type: .pig, level: 7),
            MonsterCode(type: .eyes, level: 7),
            MonsterCode(type: .eyes, level: 7),
            MonsterCode(type: .pig, level: 7),
            MonsterCode(type: .pig, level: 7),
            MonsterCode(type: .eyes, level: 7),
            MonsterCode(type: .eyes, level: 7),
            MonsterCode(type: .pig, level: 7),
            MonsterCode(type: .pig, level: 7),
            MonsterCode(type: .devil, level: 7),
            MonsterCode(type: .devil, level: 7),
            MonsterCode(type: .devil, level: 8),
            MonsterCode(type: .devil, level: 8)]),  // 68
        Wave(MonsterCode: [
            MonsterCode(type: .pig, level: 7),
            MonsterCode(type: .pig, level: 7),
            MonsterCode(type: .elephant, level: 7),
            MonsterCode(type: .elephant, level: 7),
            MonsterCode(type: .pig, level: 7),
            MonsterCode(type: .pig, level: 7),
            MonsterCode(type: .elephant, level: 7),
            MonsterCode(type: .elephant, level: 7),
            MonsterCode(type: .pig, level: 7),
            MonsterCode(type: .pig, level: 7),
            MonsterCode(type: .elephant, level: 7),
            MonsterCode(type: .elephant, level: 7),
            MonsterCode(type: .pig, level: 7),
            MonsterCode(type: .pig, level: 7),
            MonsterCode(type: .elephant, level: 7),
            MonsterCode(type: .elephant, level: 7),
            MonsterCode(type: .devil, level: 7),
            MonsterCode(type: .devil, level: 7),
            MonsterCode(type: .devil, level: 8),
            MonsterCode(type: .devil, level: 8)]),  // 69
        Wave(MonsterCode: [
            MonsterCode(type: .elephant, level: 7),
            MonsterCode(type: .elephant, level: 7),
            MonsterCode(type: .devil, level: 7),
            MonsterCode(type: .devil, level: 7),
            MonsterCode(type: .elephant, level: 7),
            MonsterCode(type: .elephant, level: 7),
            MonsterCode(type: .devil, level: 7),
            MonsterCode(type: .devil, level: 7),
            MonsterCode(type: .elephant, level: 7),
            MonsterCode(type: .elephant, level: 7),
            MonsterCode(type: .devil, level: 7),
            MonsterCode(type: .devil, level: 7),
            MonsterCode(type: .elephant, level: 7),
            MonsterCode(type: .elephant, level: 7),
            MonsterCode(type: .devil, level: 7),
            MonsterCode(type: .devil, level: 7),
            MonsterCode(type: .devil, level: 7),
            MonsterCode(type: .devil, level: 7),
            MonsterCode(type: .devil, level: 8),
            MonsterCode(type: .devil, level: 8)])]  // 70
)
